-- select * from employees where firstName = 'Jeff';
-- select * from employees where firstName like 'A%';
-- select * from employees where lastName like 'p%';
-- select * from customers where customerName like '%co.';
-- select * from customers where customerName like 'c%co.';
-- select * from customers where addressLine1 like '%56%';
-- select * from customers where customerName like '_A%';
-- select * from customers where customerName like 'C%o_';
-- select * from customers where contactFirstName like '_e%e_';
select * from customers where contactFirstName like '_____';